"use strict";
const $=id=>document.getElementById(id),roundMin=ms=>Math.round(ms/60000),uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;const SENDER=uid();let eventSource=null,remote=null,lastMessage=0,lastNotified=localStorage.getItem("lastNotifiedToken")||"",registration=null,installPrompt=null;
function normalize(v){return String(v||"").trim().replace(/[^A-Za-z0-9_-]/g,"").slice(0,48)}function topic(){const c=normalize($("codeInput").value);return c?`study_timer_${c}`:""}
async function publish(kind,data={}){if(!topic())return;try{await fetch(`https://ntfy.sh/${topic()}`,{method:"POST",body:JSON.stringify({app:"study-timer-sync-v1",kind,sender:SENDER,at:Date.now(),...data}),headers:{"Content-Type":"text/plain;charset=UTF-8","Cache":"no","Firebase":"no"}})}catch(_){setConnection("Sync offline","error")}}
function setConnection(text,cls=""){$("connectionStatus").textContent=text;$("connectionStatus").className=`status ${cls}`}
function connect(){const c=normalize($("codeInput").value);if(!c){setConnection("Code fehlt","error");return}$("codeInput").value=c;localStorage.setItem("studyTimerCompanionCode",c);eventSource?.close();setConnection("Verbinde …");eventSource=new EventSource(`https://ntfy.sh/${topic()}/sse`);eventSource.onopen=()=>{setConnection("Verbunden","connected");publish("companion_ready");publish("request_state")};eventSource.onmessage=e=>{try{const env=JSON.parse(e.data);if(env.event!=="message")return;const m=JSON.parse(env.message);if(m.app!=="study-timer-sync-v1"||m.sender===SENDER)return;lastMessage=Date.now();setConnection("Verbunden","connected");if(m.kind==="state"){remote=m.state;render()}else if(m.kind==="finished")notifyOnce(m.segmentToken,m.configuredMs,m.segmentMs)}catch(_){}};eventSource.onerror=()=>setConnection("Verbindung wird neu aufgebaut","error")}
function disconnect(){eventSource?.close();eventSource=null;remote=null;localStorage.removeItem("studyTimerCompanionCode");$("codeInput").value="";setConnection("Nicht verbunden");render()}
function formatSw(ms){const c=Math.floor(ms/10),cs=c%100,s=Math.floor(c/100),sec=s%60,m=Math.floor(s/60),min=m%60,h=Math.floor(m/60);return{main:[h,min,sec].map(x=>String(x).padStart(2,"0")).join(":"),frac:String(cs).padStart(2,"0")}}
function formatTimer(ms){const s=Math.max(0,Math.ceil(ms/1000));return[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function render(){if(!remote){$("swMain").textContent="00:00:00";$("swFraction").textContent=".00";$("timerDisplay").textContent="00:00:00";$("swStatus").textContent="—";$("timerStatus").textContent="—";$("durationInfo").textContent="Warte auf Daten aus Notion.";return}const now=Date.now(),sw=remote.swRunning?remote.swElapsed+now-remote.swStartedAt:remote.swElapsed,f=formatSw(Math.max(0,sw)),remaining=remote.timerRunning?Math.max(0,remote.timerEnd-now):remote.remainingMs;$("swMain").textContent=f.main;$("swFraction").textContent="."+f.frac;$("swStatus").textContent=remote.swRunning?"Läuft":(sw>0?"Pausiert":"Bereit");$("timerDisplay").textContent=formatTimer(remaining);$("timerStatus").textContent=remote.timerRunning?"Läuft":(remaining>0?"Pausiert":"Fertig");$("durationInfo").textContent=`Eingestellt: ${roundMin(remote.configuredMs)} Minuten`;if(remote.timerRunning&&remaining<=0&&remote.segmentToken){const seg=Math.max(0,remote.timerEnd-remote.segmentStartedAt);notifyOnce(remote.segmentToken,remote.configuredMs,seg);remote.timerRunning=false}}
async function notifyOnce(token,configuredMs,segmentMs){if(!token||token===lastNotified)return;lastNotified=token;localStorage.setItem("lastNotifiedToken",token);if(!$("notifyEnabled").checked||!("Notification"in window)||Notification.permission!=="granted")return;const title=`${roundMin(configuredMs)}/${roundMin(segmentMs)} Minuten Timer abgelaufen`,options={body:"Dein Lern-Timer ist beendet.",icon:"icon-192.png",badge:"icon-192.png",tag:`study-timer-${token}`,renotify:true,data:{url:"./companion.html"}};try{const r=registration||await navigator.serviceWorker.ready;await r.showNotification(title,options)}catch(_){try{new Notification(title,options)}catch(__){}}}
function updateNotify(){if(!("Notification"in window)){$("notifyStatus").textContent="Nicht unterstützt";$("notifyEnabled").checked=false;return}if(Notification.permission==="denied"){$("notifyStatus").textContent="Blockiert";$("notifyEnabled").checked=false;return}$("notifyStatus").textContent=$("notifyEnabled").checked&&Notification.permission==="granted"?"An":"Aus"}
async function changeNotify(){if(!$("notifyEnabled").checked){localStorage.setItem("studyTimerNotify","false");updateNotify();return}try{const p=Notification.permission==="default"?await Notification.requestPermission():Notification.permission;$("notifyEnabled").checked=p==="granted";localStorage.setItem("studyTimerNotify",String(p==="granted"))}catch(_){$("notifyEnabled").checked=false}updateNotify()}
async function init(){if("serviceWorker"in navigator){try{registration=await navigator.serviceWorker.register("sw.js");await navigator.serviceWorker.ready}catch(_){}}const c=localStorage.getItem("studyTimerCompanionCode")||"";$("codeInput").value=c;$("notifyEnabled").checked=localStorage.getItem("studyTimerNotify")==="true"&&("Notification"in window)&&Notification.permission==="granted";updateNotify();if(c)connect();setInterval(render,200);setInterval(()=>{if(eventSource&&lastMessage&&Date.now()-lastMessage>5*60*1000)publish("companion_ping")},5*60*1000)}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("installButton").classList.remove("hidden")});$("installButton").onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("installButton").classList.add("hidden")};$("connectButton").onclick=connect;$("disconnectButton").onclick=disconnect;$("notifyEnabled").onchange=changeNotify;init();