"use strict";
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.min(Math.max(Number(v)||0,a),b);const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;const SENDER=uid();
let audioContext,swFrame,timerInterval,alarmInterval,meditationNodes=null,bellInterval=null,eventSource=null,lastCompanionSeen=0;
const state={swRunning:false,swStartedAt:0,swElapsed:0,timerRunning:false,timerEnd:0,configuredMs:25*60000,remainingMs:25*60000,segmentStartedAt:null,segmentToken:null,masterPaused:false,resumeSw:false,resumeTimer:false};
function audio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();return audioContext}
function randomCode(){const b=new Uint8Array(18);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(36).padStart(2,"0")).join("").slice(0,32)}
function getCode(){let c=localStorage.getItem("studyTimerSyncCode");if(!c){c=randomCode();localStorage.setItem("studyTimerSyncCode",c)}return c}
function topic(){return `study_timer_${getCode()}`}
function currentSw(){return state.swRunning?state.swElapsed+Date.now()-state.swStartedAt:state.swElapsed}
function snapshot(){return{swRunning:state.swRunning,swStartedAt:state.swStartedAt,swElapsed:state.swElapsed,timerRunning:state.timerRunning,timerEnd:state.timerEnd,configuredMs:state.configuredMs,remainingMs:state.timerRunning?Math.max(0,state.timerEnd-Date.now()):state.remainingMs,segmentStartedAt:state.segmentStartedAt,segmentToken:state.segmentToken,sentAt:Date.now()}}
async function publish(kind,data={}){try{await fetch(`https://ntfy.sh/${topic()}`,{method:"POST",body:JSON.stringify({app:"study-timer-sync-v1",kind,sender:SENDER,at:Date.now(),...data}),headers:{"Content-Type":"text/plain;charset=UTF-8","Cache":"no","Firebase":"no"}})}catch(e){setSyncStatus("Sync offline","error")}}
function publishState(){publish("state",{state:snapshot()})}
function connectRelay(){eventSource?.close();$("syncCode").value=getCode();eventSource=new EventSource(`https://ntfy.sh/${topic()}/sse`);eventSource.onmessage=e=>{try{const env=JSON.parse(e.data);if(env.event!=="message")return;const m=JSON.parse(env.message);if(m.app!=="study-timer-sync-v1"||m.sender===SENDER)return;if(m.kind==="companion_ready"||m.kind==="companion_ping"){lastCompanionSeen=Date.now();setSyncStatus("Verbunden","connected");publishState()}else if(m.kind==="request_state")publishState()}catch(_){}};eventSource.onerror=()=>setSyncStatus("Verbindung wird neu aufgebaut","error")}
function setSyncStatus(text,cls=""){$("syncStatus").textContent=text;const card=document.querySelector(".sync-card");card.classList.remove("connected","error");if(cls)card.classList.add(cls)}
setInterval(()=>{if(lastCompanionSeen&&Date.now()-lastCompanionSeen>6*60*1000)setSyncStatus("Warte auf App")},30000);
function formatSw(ms){const c=Math.floor(ms/10),cs=c%100,s=Math.floor(c/100),sec=s%60,m=Math.floor(s/60),min=m%60,h=Math.floor(m/60);return{main:[h,min,sec].map(x=>String(x).padStart(2,"0")).join(":"),frac:String(cs).padStart(2,"0")}}
function renderSw(){const f=formatSw(currentSw());$("swMain").textContent=f.main;$("swFraction").textContent="."+f.frac;if(state.swRunning)swFrame=requestAnimationFrame(renderSw)}
function brown(ctx,seconds=5){const n=Math.floor(ctx.sampleRate*seconds),buf=ctx.createBuffer(1,n,ctx.sampleRate),o=buf.getChannelData(0);let last=0;for(let i=0;i<n;i++){last=(last+.025*(Math.random()*2-1))/1.025;o[i]=last*3.2}return buf}
function bell(){if(!meditationNodes||!state.swRunning)return;const ctx=audio(),now=ctx.currentTime,g=ctx.createGain(),f=ctx.createBiquadFilter();f.type="lowpass";f.frequency.value=2200;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.12,now+.035);g.gain.exponentialRampToValueAtTime(.0001,now+5.5);[261.63,523.25,783.99].forEach((hz,i)=>{const o=ctx.createOscillator(),pg=ctx.createGain();o.type=i?"triangle":"sine";o.frequency.value=hz;pg.gain.value=[.65,.22,.09][i];o.connect(pg).connect(f);o.start(now);o.stop(now+5.7)});f.connect(g).connect(meditationNodes.master)}
function startMeditation(){if(meditationNodes||!state.swRunning||!$("meditationEnabled").checked||Number($("meditationVolume").value)<=0)return;const ctx=audio(),master=ctx.createGain(),comp=ctx.createDynamicsCompressor(),df=ctx.createBiquadFilter(),dg=ctx.createGain(),nf=ctx.createBiquadFilter(),ng=ctx.createGain(),lfo=ctx.createOscillator(),lg=ctx.createGain(),os=[];comp.threshold.value=-18;comp.ratio.value=5;df.type="lowpass";df.frequency.value=1200;nf.type="lowpass";nf.frequency.value=900;dg.gain.value=.76;ng.gain.value=.16;[{f:110,t:"sine",g:.34},{f:164.81,t:"sine",g:.18},{f:220,t:"triangle",g:.075},{f:329.63,t:"sine",g:.035}].forEach(s=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=s.t;o.frequency.value=s.f;g.gain.value=s.g;o.connect(g).connect(df);o.start();os.push(o)});const noise=ctx.createBufferSource();noise.buffer=brown(ctx);noise.loop=true;noise.connect(nf).connect(ng);noise.start();lfo.frequency.value=.085;lg.gain.value=.055;lfo.connect(lg).connect(dg.gain);lfo.start();df.connect(dg).connect(master);ng.connect(master);master.connect(comp).connect(ctx.destination);master.gain.setValueAtTime(.0001,ctx.currentTime);master.gain.exponentialRampToValueAtTime(Number($("meditationVolume").value),ctx.currentTime+.8);meditationNodes={master,os,noise,lfo};setTimeout(bell,1600);bellInterval=setInterval(bell,18000)}
function stopMeditation(){if(!meditationNodes||!audioContext)return;const n=meditationNodes;meditationNodes=null;clearInterval(bellInterval);const now=audioContext.currentTime;try{n.master.gain.cancelScheduledValues(now);n.master.gain.setValueAtTime(Math.max(.0001,n.master.gain.value),now);n.master.gain.exponentialRampToValueAtTime(.0001,now+.35);n.os.forEach(o=>o.stop(now+.4));n.noise.stop(now+.4);n.lfo.stop(now+.4)}catch(_){}}
function startSw(){if(state.swRunning)return;audio();state.swStartedAt=Date.now();state.swRunning=true;$("swToggle").textContent="Pause";$("swStatus").textContent="Läuft";startMeditation();renderSw();publishState()}
function pauseSw(label="Pausiert"){if(!state.swRunning)return;state.swElapsed=currentSw();state.swStartedAt=0;state.swRunning=false;cancelAnimationFrame(swFrame);stopMeditation();$("swToggle").textContent="Weiter";$("swStatus").textContent=label;renderSw();publishState()}
function resetSw(){state.swRunning=false;state.swElapsed=0;state.swStartedAt=0;state.resumeSw=false;cancelAnimationFrame(swFrame);stopMeditation();$("swToggle").textContent="Start";$("swStatus").textContent="Bereit";renderSw();publishState()}
function inputMs(){return(clamp($("hours").value,0,99)*3600+clamp($("minutes").value,0,59)*60+clamp($("seconds").value,0,59))*1000}
function writeInputs(ms){const s=Math.floor(Math.max(0,ms)/1000);$("hours").value=Math.floor(s/3600);$("minutes").value=Math.floor(s/60)%60;$("seconds").value=s%60}
function formatTimer(ms){const s=Math.max(0,Math.ceil(ms/1000));return[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function renderTimer(){$("timerDisplay").textContent=formatTimer(state.remainingMs)}
function playAlarm(){if(!$("alarmEnabled").checked||Number($("alarmVolume").value)<=0)return;const ctx=audio(),now=ctx.currentTime;[0,.18,.36].forEach((d,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===1?"square":"sine";o.frequency.value=i===1?880:660;g.gain.setValueAtTime(Number($("alarmVolume").value),now+d);g.gain.exponentialRampToValueAtTime(.0001,now+d+.13);o.connect(g).connect(ctx.destination);o.start(now+d);o.stop(now+d+.14)})}
function stopAlarm(){clearInterval(alarmInterval);alarmInterval=null;$("timerCard").classList.remove("finished");$("alarmStop").style.display="none"}
function startAlarm(){stopAlarm();$("timerCard").classList.add("finished");$("alarmStop").style.display="block";playAlarm();alarmInterval=setInterval(playAlarm,1100)}
function startTimer(){if(state.timerRunning)return;stopAlarm();audio();if(state.remainingMs<=0)state.remainingMs=state.configuredMs;if(state.remainingMs<=0){$("timerStatus").textContent="Zeit einstellen";return}state.segmentStartedAt=Date.now();state.segmentToken=uid();state.timerEnd=state.segmentStartedAt+state.remainingMs;state.timerRunning=true;$("timerToggle").textContent="Pause";$("timerStatus").textContent="Läuft";timerInterval=setInterval(tick,100);tick();publishState()}
function pauseTimer(label="Pausiert"){if(!state.timerRunning)return;state.remainingMs=Math.max(0,state.timerEnd-Date.now());state.timerRunning=false;state.segmentStartedAt=null;clearInterval(timerInterval);$("timerToggle").textContent="Weiter";$("timerStatus").textContent=label;renderTimer();publishState()}
function tick(){state.remainingMs=Math.max(0,state.timerEnd-Date.now());renderTimer();if(state.remainingMs<=0)finishTimer()}
function finishTimer(){const segmentMs=state.segmentStartedAt?Math.max(0,Date.now()-state.segmentStartedAt):0,token=state.segmentToken;state.timerRunning=false;state.remainingMs=0;state.segmentStartedAt=null;state.resumeTimer=false;clearInterval(timerInterval);$("timerToggle").textContent="Start";$("timerStatus").textContent="Fertig";renderTimer();startAlarm();publish("finished",{configuredMs:state.configuredMs,segmentMs,segmentToken:token});publishState();updateMaster()}
function resetTimer(){state.timerRunning=false;state.segmentStartedAt=null;state.remainingMs=state.configuredMs;state.resumeTimer=false;clearInterval(timerInterval);stopAlarm();$("timerToggle").textContent="Start";$("timerStatus").textContent=state.remainingMs>0?"Bereit":"Zeit einstellen";renderTimer();publishState()}
function syncInputs(){if(state.timerRunning)return;stopAlarm();state.configuredMs=inputMs();state.remainingMs=state.configuredMs;$("timerStatus").textContent=state.remainingMs>0?"Bereit":"Zeit einstellen";renderTimer();updateMaster();publishState()}
function adjustTimer(min){stopAlarm();const d=Number(min)*60000;state.configuredMs=Math.max(0,state.configuredMs+d);state.remainingMs=Math.max(0,state.remainingMs+d);writeInputs(state.configuredMs);if(state.timerRunning){if(state.remainingMs<=0){finishTimer();return}state.timerEnd=Date.now()+state.remainingMs;$("timerStatus").textContent="Läuft"}else $("timerStatus").textContent=state.remainingMs>0?(state.masterPaused?"Gemeinsam pausiert":"Bereit"):"Zeit einstellen";renderTimer();updateMaster();publishState()}
const masters=[...document.querySelectorAll(".master-toggle")];function updateMaster(){const label=state.masterPaused?"▶ Beide fortsetzen":(state.swRunning||state.timerRunning?"⏸ Beide pausieren":"▶ Beide starten");masters.forEach(b=>b.textContent=label);$("swToggle").disabled=state.masterPaused;$("timerToggle").disabled=state.masterPaused}
function startBoth(){if(!state.swRunning)startSw();if(!state.timerRunning)startTimer();updateMaster()}
function pauseBoth(){state.resumeSw=state.swRunning;state.resumeTimer=state.timerRunning;if(state.swRunning)pauseSw("Gemeinsam pausiert");if(state.timerRunning)pauseTimer("Gemeinsam pausiert");stopAlarm();state.masterPaused=true;updateMaster();publishState()}
function resumeBoth(){state.masterPaused=false;const a=state.resumeSw,b=state.resumeTimer;state.resumeSw=state.resumeTimer=false;if(a)startSw();if(b&&state.remainingMs>0)startTimer();updateMaster();publishState()}
function toggleMaster(){audio();if(state.masterPaused)resumeBoth();else if(state.swRunning||state.timerRunning)pauseBoth();else startBoth()}
function resetBoth(){state.masterPaused=false;state.resumeSw=state.resumeTimer=false;resetSw();resetTimer();updateMaster();publishState()}
$("swToggle").onclick=()=>{if(state.masterPaused)return;state.swRunning?pauseSw():startSw();updateMaster()};$("swReset").onclick=()=>{resetSw();updateMaster()};$("meditationEnabled").onchange=()=>state.swRunning&&$("meditationEnabled").checked?startMeditation():stopMeditation();$("meditationVolume").oninput=()=>{const v=Number($("meditationVolume").value);if(v<=0)stopMeditation();else if(meditationNodes)meditationNodes.master.gain.setTargetAtTime(v,audioContext.currentTime,.06);else if(state.swRunning)startMeditation()};[$("hours"),$("minutes"),$("seconds")].forEach(i=>i.oninput=syncInputs);document.querySelectorAll("[data-minutes]").forEach(b=>b.onclick=()=>adjustTimer(b.dataset.minutes));$("timerToggle").onclick=()=>{if(state.masterPaused)return;state.timerRunning?pauseTimer():startTimer();updateMaster()};$("timerReset").onclick=()=>{resetTimer();updateMaster()};$("alarmStop").onclick=stopAlarm;masters.forEach(b=>b.onclick=toggleMaster);document.querySelectorAll(".master-reset").forEach(b=>b.onclick=resetBoth);
$("copyCode").onclick=async()=>{try{await navigator.clipboard.writeText(getCode());$("copyCode").textContent="Kopiert";setTimeout(()=>$("copyCode").textContent="Code kopieren",1200)}catch(_){$("syncCode").select();document.execCommand("copy")}};$("newCode").onclick=()=>{if(!confirm("Neuen Sync-Code erstellen? Die Begleit-App muss danach neu verbunden werden."))return;localStorage.setItem("studyTimerSyncCode",randomCode());lastCompanionSeen=0;setSyncStatus("Warte auf App");connectRelay()};
$("syncCode").value=getCode();connectRelay();renderSw();renderTimer();updateMaster();publishState();